# global default
freebsd_instance:
  image: freebsd-10-4-release-amd64
container:
  image: gradle:jdk8

build_task:
  gradle_cache:
    folder: ~/.gradle/caches
  build_script:
    - ./gradlew build -x check
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete