language: java

sudo: required

dist: trusty

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

before_install:
 - chmod +x ./gradlew
 - sudo apt-get install libreoffice

script:
  - ./gradlew build --stacktrace
  
after_success:
  - ./gradlew jacocoTestReport coveralls