logging:
  level:
    root: INFO
    org.jodconverter: DEBUG
    
jodconverter:
  enabled: true
  port-numbers: 2005
  kill-existing-process: true
  process-timeout: 180000
  process-retry-interval: 1000
  max-tasks-per-process: 20
  task-execution-timeout: 60000
  task-queue-timeout: 60000