server:
  port: 8080
  
spring:
  http:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    name: JODConverter Sample Rest Api

jodconverter:
  local:
    enabled: true
    port-numbers: 2002,2003
  
logging:
  level:
    org.jodconverter: debug
